#ifndef SRT_CONFIG_H
#define SRT_CONFIG_H

#include "algo.h"
#include <stdbool.h>
#include <stdint.h>

typedef struct
{
    SRT_Algorithm algo;      // selected sorting algorithm to visualize
    uint8_t animation_delay; // animation delay between each step of the sorting algorithm
    uint16_t arr_size;       // size of the array to sort
    bool is_sound_on;        // toggle sound on/off
    bool is_compare_algo;    // toggle sorting algorithm comparison on/off
    SRT_Algorithm algo_sec;  // secondary sorting algorithm to run if is_compare_algo is true
    char *ini_path;          // path to the ini file generated by imgui to save UI layout
} SRT_Config;

/*
 * Setup SRT_Config obj with default values
 *
 * @param cfg
 */
void srt_config_setup(SRT_Config *cfg);

/*
 * Deallocate memory from SRT_Config obj.
 *
 * @param cfg
 */
void srt_config_teardown(SRT_Config *cfg);

#endif // SRT_CONFIG_H
